### ISSUE TITLE
Weird Sidebar

### ISSUE THREAD

**Issue by snjyr123** [material-ocean/Spotify-Theme#11]
I have the latest version of Material-Ocean, Spicetify, and Spotify, and I have a weird glitch where my sidebar for spotify looks like this: 
<img width="172" alt="image" src="https://user-images.githubusercontent.com/83570596/144668197-fb48fb62-f232-41ad-bad0-1048a07026af.png">
Is there any way I could fix it?

**Comment by Blacksuan19** [comment]
What's weird about it?

**Comment by snjyr123** [comment]
I wasn't sure if the album artwork was supposed to show instead of the name of the playlist in the playlist selector.

**Comment by Blacksuan19** [comment]
Oh that, yeah it's supposed to show the name and not the artwork, can you do a clean install and check again

**Comment by snjyr123** [comment]
Yep that fixed it, thanks!!
