### ISSUE TITLE
Theme breaks spotify

### ISSUE THREAD

**Issue by Xoroxa** [material-ocean/Spotify-Theme#2]
The username in the top right doesn't show up and in the bottom left the image breaks once you enlarge it.

![image](https://user-images.githubusercontent.com/34523791/108146382-2224a200-709b-11eb-8ac5-be76267ced1f.png)

**Comment by Blacksuan19** [comment]
the username is hidden on purpose, to show it you can edit the css file and delete `.profile.content-top-bar__profile-link` from `display: none`.
will look into the song art on the bottom left

**Comment by Blacksuan19** [comment]
fixed in the latest commits.
![image](https://user-images.githubusercontent.com/10248473/108156607-f269ae80-711b-11eb-9c48-bddfe90bbdf2.png)

**Comment by Xoroxa** [comment]
Thanks
