### ISSUE TITLE
A few problems with layout

### ISSUE THREAD

**Issue by xwillq** [material-ocean/Spotify-Theme#3]
## Text in card title an card info sometimes has different alignment
In search:

![image](https://user-images.githubusercontent.com/38136135/111029423-18d6ed00-842f-11eb-98b0-e294ce7e1bec.png)
![image](https://user-images.githubusercontent.com/38136135/111029470-53408a00-842f-11eb-88e1-e2ad94b450b3.png)
On an artist page:

![image](https://user-images.githubusercontent.com/38136135/111029451-3ad06f80-842f-11eb-94b3-c82b33985621.png)
## Top of album images get cropped on hover
| Normal | Hover |
|---|---|
|![image](https://user-images.githubusercontent.com/38136135/111029572-ec6fa080-842f-11eb-99c6-7320f0a8b970.png)|![image](https://user-images.githubusercontent.com/38136135/111029575-f396ae80-842f-11eb-9b8a-8ea15c8e3e2b.png)|
## Text in Local Files is messed up
![image](https://user-images.githubusercontent.com/38136135/111029656-66a02500-8430-11eb-8ef7-848c088e9f23.png)

This happens only with albums and playlists in first row of the table

## Sidescroll doesn't work on discover page
![image](https://user-images.githubusercontent.com/38136135/111029716-b252ce80-8430-11eb-8ab1-1025ff840adc.png)

## Clear recent searches button gets under player controls 
![image](https://user-images.githubusercontent.com/38136135/111029767-03fb5900-8431-11eb-96c0-3a1590628dd5.png)

**Comment by Blacksuan19** [comment]
- [x] Text in card title an card info sometimes has different alignment - Fixed
- [x] Text in Local Files is messed up - Fixed
- [x] Top of album images get cropped on hover - Fixed
- [x] Sidescroll doesn't work on discover page - use the buttons on top right
- [x] Clear recent searches button gets under player controls - only appears when the window size is very small and cannot be avoided

i have pushed fixes for 3 of the above issues, try now and see if they're still there

**Comment by xwillq** [comment]
Problem with `Clear recent searches` appears on 1920*1080 laptop screen with 125% scaling, I don't think that this is a very small window size. It can be fixed by adding `margin-bottom` to `RecentlySearched` class (although I'm not sure if this is the best place to add margin).

Everything else is fine, thanks!

**Comment by Blacksuan19** [comment]
my display is 768x and with both maximized or floating the button is there at the same place, I need to have the window really small to face this issue 
![2021-03-15_02-00](https://user-images.githubusercontent.com/10248473/111078929-bff07d00-8532-11eb-8d9f-ff1ed158ee09.png)

**Comment by xwillq** [comment]
Or it could be filled with a lot of elements, which is probably a common thing

![image](https://user-images.githubusercontent.com/38136135/111107715-f5748500-8589-11eb-9b52-ccaa4cd94902.png)

**Comment by Blacksuan19** [comment]
fixed the button issue, try with the latest commit

**Comment by xwillq** [comment]
Looks good now
