### ISSUE TITLE
Little Red Lip on the Top Left Corner

### ISSUE THREAD

**Issue by snjyr123** [material-ocean/Spotify-Theme#5]
There is a little red lip on the top right corner after I got the new update for material-ocean and spicetify 2.2.2, how would I remove that?

![image](https://user-images.githubusercontent.com/83570596/118903948-6b74cf80-b8de-11eb-9f21-cd55c514b855.png)

**Comment by Blacksuan19** [comment]
I don't see that here, try reinstalling the theme, that looks like the selection card which is not even red 

_Sent from my POCO X2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by snjyr123** [comment]
Thank you!! Redownloading worked for me. The theme looks continues to look amazing!!! :)
